CREATE DATABASE testing;
CREATE USER tester WITH ENCRYPTED PASSWORD 'interview';
GRANT ALL PRIVILEGES ON DATABASE testing TO tester;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA testing TO tester;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA testing TO tester;
ALTER USER tester SET search_path = testing;