framework:
  cache:
    prefix_seed: intrv

    app: cache.adapter.redis
    default_redis_provider: 'redis://%env(REDIS_PASSWORD)%@%env(REDIS_HOST)%:%env(REDIS_PORT)%'
    pools:
      doctrine.second_level_cache_pool:
        adapter: cache.app
      doctrine.result_cache_pool:
        adapter: cache.adapter.redis
      doctrine.system_cache_pool:
        adapter: cache.adapter.redis