# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
  secret: '%env(APP_SECRET)%'
  csrf_protection: true
  http_method_override: false
  handle_all_throwables: true
  esi: true
  fragments: true
  # Enables session support. Note that the session will ONLY be started if you read or write from it.
  # Remove or comment this section to explicitly disable session support.
  session:
    handler_id: null
    cookie_secure: auto
    cookie_samesite: lax
    storage_factory_id: session.storage.factory.native

  php_errors:
    log: true
  http_client:
    scoped_clients:
      auth-api:
        base_uri: '%env(AUTH_API_HOST)%'
        auth_basic: '%env(AUTH_API_AUTH_CREDENTIALS)%'
        headers:
          Accept: 'application/json'
          Content-Type: 'application/json'
          'User-Agent': 'RsShop'
      users-api:
        base_uri: '%env(AUTH_API_HOST)%'
        headers:
          Accept: 'application/json'
          Content-Type: 'application/json'
          'User-Agent': 'RsShop'