# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
  secret: '%env(APP_SECRET)%'
  csrf_protection: true
  http_method_override: false
  handle_all_throwables: true
  esi: true
  fragments: true
  # Enables session support. Note that the session will ONLY be started if you read or write from it.
  # Remove or comment this section to explicitly disable session support.
  session:
    handler_id: null
    cookie_secure: auto
    cookie_samesite: lax
    storage_factory_id: session.storage.factory.native

  php_errors:
    log: true
  http_client:
    scoped_clients:
      auth-api:
        base_uri: 'https://auth-api.salwa.com.pl'
        auth_basic: 'interview:interview'
        headers:
          Accept: 'application/json'
          Content-Type: 'application/json'
          'User-Agent': 'Shopping app'
      users-api:
        base_uri: 'https://auth-api.salwa.com.pl'
        headers:
          Accept: 'application/json'
          Content-Type: 'application/json'
          'User-Agent': 'Shopping app'
when@dev:
  framework:
    http_client:
      scoped_clients:
        auth-api:
          base_uri: 'http://0.0.0.0:8011'
          auth_basic: 'interview:interview'
          headers:
            Accept: 'application/json'
            Content-Type: 'application/json'
            'User-Agent': 'Shopping app'
        users-api:
          base_uri: 'http://0.0.0.0:8011'
          headers:
            Accept: 'application/json'
            Content-Type: 'application/json'
            'User-Agent': 'Shopping app'