twig:
  default_path: '%kernel.project_dir%/templates'
  form_themes: [ 'bootstrap_5_layout.html.twig' ]
  globals:
    current_cart: '@App\Service\CartService'

when@test:
  twig:
    strict_variables: true
