twig:
  default_path: '%kernel.project_dir%/templates'
  form_themes: [ 'bootstrap_5_layout.html.twig' ]
  globals:
    cartService: '@App\Service\CartService'
    mailer_client_url: '%env(MAILER_CLIENT_URL)%'

when@test:
  twig:
    strict_variables: true
