---
engines:
  phpcs:
    php_version: 8.2
  phpmd:

languages:
  css:
    extensions:
      - ".scss"

exclude_paths:
  - "config/**"
  - "docker/**"
  - "migrations/**"
  - "src/Protobuf/**/*"
  - "templates/**"
  - "vendor/**"
  - "public/**"
  - "assets/**"
  - "**/*.twig"
