---
version: "2"
plugins:
  duplication:
    enabled: false
    config:
      languages:
        php:
          mass_threshold: 80
  editorconfig:
    enabled: true
    channel: beta
    config:
      editorconfig: .editorconfig
  fixme:
    enabled: true
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
      rulesets: "config/analysis/phpmd.xml"
  git-legal:
    enabled: true
  markdownlint:
    enabled: true
  phpcodesniffer:
    enabled: true
    channel: beta
    config:
      ignore_warnings: true
      file_extensions: "php"
      standard: "config/analysis/phpcs.xml"
  sonar-php:
    enabled: true
    config:
      minimum_severity: critical
checks:
  argument-count:
    config:
      threshold: 6
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 250
  method-complexity:
    config:
      threshold: 5
  method-count:
    config:
      threshold: 22
  method-lines:
    config:
      threshold: 40
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
  similar-code:
    config:
      threshold: 45 # language-specific defaults. an override will affect all languages.
  identical-code:
    config:
      threshold: # language-specific defaults. an override will affect all languages.
exclude_patterns:
  - ".idea/"
  - assets/
  - bin/
  - build/
  - config/
  - public/
  - migrations/
  - src/Protobuf/
  - templates/
  - tests/
  - node_modules/
  - translations/
  - var/
  - vendor/
  - config/
  - Protobuf
  - node_modules
  - Tests/
  - vendor
