---
version: 2
plugins:
  duplication:
    enabled: false
    config:
      languages:
        php:
          mass_threshold: 80
  editorconfig:
    enabled: true
  fixme:
    enabled: true
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
      rulesets: "reports/config/phpmd.xml"
  git-legal:
    enabled: true
  markdownlint:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      standard: "reports/config/phpcs.xml"
  sonar-php:
    enabled: true
    config:
      minimum_severity: critical
  checkstyle:
    enabled: true
    config:
      file: "reports/results.phpstan.checkstyle.xml"
checks:
  argument-count:
    config:
      threshold: 6
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 250
  method-complexity:
    config:
      threshold: 5
  method-count:
    config:
      threshold: 22
  method-lines:
    config:
      threshold: 40
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
  similar-code:
    config:
      threshold: 45 # language-specific defaults. an override will affect all languages.
  identical-code:
    config:
      threshold: # language-specific defaults. an override will affect all languages.
exclude_patterns:
  - ".idea/"
  - bin/
  - build/
  - config/
  - public/
  - migrations/
  - src/Protobuf/
  - templates/
  - tests/
  - translations/
  - var/
  - vendor/