version: '3'

services:
  php_mailhog:
    image: mailhog/mailhog
    container_name: php_mailhog
    ports:
      - "11025:1025" # smtp server
      - "18025:8025" # web ui
    networks:
      interview-net:
        aliases:
          - iphpmailhog
