version: '3'

services:
  php_mailhog:
    image: mailhog/mailhog
    container_name: php_mailhog
    ports:
      - "11025:1025" # smtp server
      - "18025:8025" # web ui
    networks:
      interview-net:
        aliases:
          - iphpmailhog
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=interview
      - RABBITMQ_DEFAULT_PASS=interview
      - RABBITMQ_DEFAULT_VHOST=interview
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 1s
      timeout: 3s
      retries: 30
    volumes:
      - ./docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.config:ro
      - ./docker/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    networks:
      interview-net:
        aliases:
          - irabbitmq