version: '3.9'

services:
  php:
    container_name: php
    image: rafalsalwa/interview-app-php:latest
    volumes:
      - ../:/var/www/symfony
      - symfony_app_var:/var/www/symfony/var
      - symfony_app_vendor:/var/www/symfony/vendor
    networks:
      interview-net:
        aliases:
          - iphp
  nginx:
    container_name: nginx
    build:
      context: ./docker/nginx
    volumes:
      - ../:/var/www/symfony
      - symfony_app_var:/var/www/symfony/var
      - symfony_app_vendor:/var/www/symfony/vendor
    ports:
      - 80:80
    networks:
      interview-net:
        aliases:
          - inginx

volumes:
  symfony_app_var:
  symfony_app_vendor:

networks:
  interview-net:
    name: interview-net
    driver: bridge
    enable_ipv6: false