version: '3.9'

services:
  php:
    container_name: php
    image: rafalsalwa/interview-app-php:latest
    volumes:
      - .:/var/www/symfony
    networks:
      interview-net:
        aliases:
          - iphp
  nginx:
    container_name: nginx
    image: nginx:1.25-alpine
    volumes:
      - .:/var/www/symfony
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/interview_host.conf:/etc/nginx/sites-enabled/interview_host.conf
      - ./docker/nginx/fragments/:/etc/nginx/fragments/
      - ./docker/nginx/keys/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - ./docker/nginx/keys/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
      - ./docker/nginx/keys/dhparam.pem:/etc/ssl/certs/dhparam.pem
    ports:
      - 80:80
      - 443:443
      - 8443:8443
    networks:
      interview-net:
        aliases:
          - inginx

networks:
  interview-net:
    name: interview-net
    driver: bridge
    enable_ipv6: false