version: '3.9'

services:
  php:
    container_name: php
    image: rafalsalwa/interview-app-php:latest
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - .:/var/www/symfony
    networks:
      interview-net:
        aliases:
          - iphp
  postgres_php:
    container_name: postgres_php
    image: postgres:15-alpine3.18
    user: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./docker/pg/init_db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: 'interview'
      POSTGRES_PASSWORD: 'interview'
      POSTGRES_DB: 'interview'
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h localhost -U interview -d interview" ]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
    networks:
      interview-net:
        aliases:
          - ipostgres_php
volumes:
  cache:
    driver: local
  pg-data:

networks:
  interview-net:
    name: interview-net
    driver: bridge
    enable_ipv6: false