<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: basic_type.proto

namespace App\Protobuf\GPBMetadata;

class BasicType
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac8010a1062617369635f747970652e70726f746f120a696e74727670726f746f221a0a09426f6f6c56616c7565120d0a0576616c7565180120012808221c0a0b537472696e6756616c7565120d0a0576616c756518012001280942665a326769746875622e636f6d2f526166616c53616c77612f696e746572766965772d6170702d7372762f696e74727670726f746fca02144170705c50726f746f6275665c4d657373616765e202184170705c50726f746f6275665c4750424d65746164617461620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

