parameters:
  paths:
    - ../../src
  exclude_files:
    - '#.*test.*#'
  formatters:
    graphviz:
      point_to_groups: true
      groups:
        Entrypoints:
          - Controllers
          - Commands
        Persistence:
          - Repositories
          - Entities
      hidden_layers:
        - Utils

  layers:
    - name: Controller
      collectors:
        - type: className
          regex: .*Controller.*
    - name: Repository
      collectors:
        - type: className
          regex: .*Repository.*
    - name: Service
      collectors:
        - type: className
          regex: .*Service.*
    - name: Entity
      collectors:
        - type: attribute
          value: Doctrine\ORM\Mapping\Entity
  ruleset:
    Controller:
      - Service
      - Repository
      - Entity
    Service:
      - Repository
    Repository:
      - Entity
