version: "3"

services:
  db:
    image: mysql:8.0.33
    container_name: pdb
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "db_app:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    networks:
      external-interview-net:
  php:
    container_name: php
    build:
      context: ./php
      args:
        TIMEZONE: ${TIMEZONE}
    volumes:
      - ../:/var/www/symfony
      - symfony_app_var:/var/www/symfony/var
      - symfony_app_vendor:/var/www/symfony/vendor
    networks:
      external-interview-net:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
    volumes:
      - ../:/var/www/symfony
      - symfony_app_var:/var/www/symfony/var
      - symfony_app_vendor:/var/www/symfony/vendor
    ports:
      - 80:80
    networks:
      external-interview-net:

volumes:
  symfony_app_var:
  symfony_app_vendor:
  db_app:

networks:
  external-interview-net:
    external: true
