<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_signin.proto

namespace App\Protobuf\Message;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>intrvproto.SignInByCodeUserInput</code>.
 */
class SignInByCodeUserInput extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string email = 1;</code>.
     */
    protected $email = '';
    /**
     * Generated from protobuf field <code>string authCode = 2;</code>.
     */
    protected $authCode = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     * @var string $email
     * @var string $authCode
     *             }
     */
    public function __construct($data = null)
    {
        \App\Protobuf\GPBMetadata\RpcSignin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string email = 1;</code>.
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Generated from protobuf field <code>string email = 1;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, true);
        $this->email = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string authCode = 2;</code>.
     *
     * @return string
     */
    public function getAuthCode()
    {
        return $this->authCode;
    }

    /**
     * Generated from protobuf field <code>string authCode = 2;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setAuthCode($var)
    {
        GPBUtil::checkString($var, true);
        $this->authCode = $var;

        return $this;
    }
}
