<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: basic_type.proto

namespace App\Protobuf\Message;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>intrvproto.StringValue</code>.
 */
class StringValue extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string value = 1;</code>.
     */
    protected $value = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     * @var string $value
     *             }
     */
    public function __construct($data = null)
    {
        \App\Protobuf\GPBMetadata\BasicType::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string value = 1;</code>.
     *
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Generated from protobuf field <code>string value = 1;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, true);
        $this->value = $var;

        return $this;
    }
}
