<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

namespace App\Protobuf\Message;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>intrvproto.UserResponse</code>.
 */
class UserResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.intrvproto.User user = 1;</code>.
     */
    protected $user = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     * @var \App\Protobuf\Message\User $user
     *                                 }
     */
    public function __construct($data = null)
    {
        \App\Protobuf\GPBMetadata\User::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.intrvproto.User user = 1;</code>.
     *
     * @return \App\Protobuf\Message\User
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Generated from protobuf field <code>.intrvproto.User user = 1;</code>.
     *
     * @param \App\Protobuf\Message\User $var
     *
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkMessage($var, \App\Protobuf\Message\User::class);
        $this->user = $var;

        return $this;
    }
}
