<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

namespace App\Protobuf\Message;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>intrvproto.UserDetails</code>.
 */
class UserDetails extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 Id = 1;</code>.
     */
    protected $Id = 0;
    /**
     * Generated from protobuf field <code>string Username = 2;</code>.
     */
    protected $Username = '';
    /**
     * Generated from protobuf field <code>string Firstname = 3;</code>.
     */
    protected $Firstname = '';
    /**
     * Generated from protobuf field <code>string Lastname = 4;</code>.
     */
    protected $Lastname = '';
    /**
     * Generated from protobuf field <code>string Email = 5;</code>.
     */
    protected $Email = '';
    /**
     * Generated from protobuf field <code>string VerificationCode = 6;</code>.
     */
    protected $VerificationCode = '';
    /**
     * Generated from protobuf field <code>string RolesJson = 7;</code>.
     */
    protected $RolesJson = '';
    /**
     * Generated from protobuf field <code>string Roles = 8;</code>.
     */
    protected $Roles = '';
    /**
     * Generated from protobuf field <code>string Role = 9;</code>.
     */
    protected $Role = '';
    /**
     * Generated from protobuf field <code>string AccessToken = 10;</code>.
     */
    protected $AccessToken = '';
    /**
     * Generated from protobuf field <code>string RefreshToken = 11;</code>.
     */
    protected $RefreshToken = '';
    /**
     * Generated from protobuf field <code>bool Verified = 12;</code>.
     */
    protected $Verified = false;
    /**
     * Generated from protobuf field <code>bool Active = 13;</code>.
     */
    protected $Active = false;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp CreatedAt = 14;</code>.
     */
    protected $CreatedAt = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp LastLogin = 15;</code>.
     */
    protected $LastLogin = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     * @var int|string                 $Id
     * @var string                     $Username
     * @var string                     $Firstname
     * @var string                     $Lastname
     * @var string                     $Email
     * @var string                     $VerificationCode
     * @var string                     $RolesJson
     * @var string                     $Roles
     * @var string                     $Role
     * @var string                     $AccessToken
     * @var string                     $RefreshToken
     * @var bool                       $Verified
     * @var bool                       $Active
     * @var \Google\Protobuf\Timestamp $CreatedAt
     * @var \Google\Protobuf\Timestamp $LastLogin
     *                                 }
     */
    public function __construct($data = null)
    {
        \App\Protobuf\GPBMetadata\User::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 Id = 1;</code>.
     *
     * @return int|string
     */
    public function getId()
    {
        return $this->Id;
    }

    /**
     * Generated from protobuf field <code>int64 Id = 1;</code>.
     *
     * @param int|string $var
     *
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->Id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Username = 2;</code>.
     *
     * @return string
     */
    public function getUsername()
    {
        return $this->Username;
    }

    /**
     * Generated from protobuf field <code>string Username = 2;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setUsername($var)
    {
        GPBUtil::checkString($var, true);
        $this->Username = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Firstname = 3;</code>.
     *
     * @return string
     */
    public function getFirstname()
    {
        return $this->Firstname;
    }

    /**
     * Generated from protobuf field <code>string Firstname = 3;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setFirstname($var)
    {
        GPBUtil::checkString($var, true);
        $this->Firstname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Lastname = 4;</code>.
     *
     * @return string
     */
    public function getLastname()
    {
        return $this->Lastname;
    }

    /**
     * Generated from protobuf field <code>string Lastname = 4;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setLastname($var)
    {
        GPBUtil::checkString($var, true);
        $this->Lastname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Email = 5;</code>.
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->Email;
    }

    /**
     * Generated from protobuf field <code>string Email = 5;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, true);
        $this->Email = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string VerificationCode = 6;</code>.
     *
     * @return string
     */
    public function getVerificationCode()
    {
        return $this->VerificationCode;
    }

    /**
     * Generated from protobuf field <code>string VerificationCode = 6;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setVerificationCode($var)
    {
        GPBUtil::checkString($var, true);
        $this->VerificationCode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string RolesJson = 7;</code>.
     *
     * @return string
     */
    public function getRolesJson()
    {
        return $this->RolesJson;
    }

    /**
     * Generated from protobuf field <code>string RolesJson = 7;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setRolesJson($var)
    {
        GPBUtil::checkString($var, true);
        $this->RolesJson = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Roles = 8;</code>.
     *
     * @return string
     */
    public function getRoles()
    {
        return $this->Roles;
    }

    /**
     * Generated from protobuf field <code>string Roles = 8;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setRoles($var)
    {
        GPBUtil::checkString($var, true);
        $this->Roles = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Role = 9;</code>.
     *
     * @return string
     */
    public function getRole()
    {
        return $this->Role;
    }

    /**
     * Generated from protobuf field <code>string Role = 9;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setRole($var)
    {
        GPBUtil::checkString($var, true);
        $this->Role = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string AccessToken = 10;</code>.
     *
     * @return string
     */
    public function getAccessToken()
    {
        return $this->AccessToken;
    }

    /**
     * Generated from protobuf field <code>string AccessToken = 10;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setAccessToken($var)
    {
        GPBUtil::checkString($var, true);
        $this->AccessToken = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string RefreshToken = 11;</code>.
     *
     * @return string
     */
    public function getRefreshToken()
    {
        return $this->RefreshToken;
    }

    /**
     * Generated from protobuf field <code>string RefreshToken = 11;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setRefreshToken($var)
    {
        GPBUtil::checkString($var, true);
        $this->RefreshToken = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool Verified = 12;</code>.
     *
     * @return bool
     */
    public function getVerified()
    {
        return $this->Verified;
    }

    /**
     * Generated from protobuf field <code>bool Verified = 12;</code>.
     *
     * @param bool $var
     *
     * @return $this
     */
    public function setVerified($var)
    {
        GPBUtil::checkBool($var);
        $this->Verified = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool Active = 13;</code>.
     *
     * @return bool
     */
    public function getActive()
    {
        return $this->Active;
    }

    /**
     * Generated from protobuf field <code>bool Active = 13;</code>.
     *
     * @param bool $var
     *
     * @return $this
     */
    public function setActive($var)
    {
        GPBUtil::checkBool($var);
        $this->Active = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp CreatedAt = 14;</code>.
     *
     * @return \Google\Protobuf\Timestamp
     */
    public function getCreatedAt()
    {
        return $this->CreatedAt;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp CreatedAt = 14;</code>.
     *
     * @param \Google\Protobuf\Timestamp $var
     *
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->CreatedAt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp LastLogin = 15;</code>.
     *
     * @return \Google\Protobuf\Timestamp
     */
    public function getLastLogin()
    {
        return $this->LastLogin;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp LastLogin = 15;</code>.
     *
     * @param \Google\Protobuf\Timestamp $var
     *
     * @return $this
     */
    public function setLastLogin($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->LastLogin = $var;

        return $this;
    }
}
