<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_signin.proto

namespace App\Protobuf\Message;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>intrvproto.VerificationCodeResponse</code>.
 */
class VerificationCodeResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string code = 1;</code>.
     */
    protected $code = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     * @var string $code
     *             }
     */
    public function __construct($data = null)
    {
        \App\Protobuf\GPBMetadata\RpcSignin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string code = 1;</code>.
     *
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Generated from protobuf field <code>string code = 1;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, true);
        $this->code = $var;

        return $this;
    }
}
