parameters:
  .container.dumper.inline_factories: true

services:
  _defaults:
    autowire: true
    autoconfigure: true
  Redis:
    class: Redis
    calls:
      - connect:
          - '%env(REDIS_HOST)%'
          - '%env(int:REDIS_PORT)%'
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
      - '../src/Tests/'
  App\ValueResolver\CartItemTypeResolver:
    tags:
      - controller.argument_value_resolver:
          name: cart_item_type
          priority: 150

  Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler:
    arguments:
      - '@Redis'
  League\Bundle\OAuth2ServerBundle\Entity\AccessToken:
    class: App\Entity\AccessToken
  League\OAuth2\Server\Repositories\AccessTokenRepositoryInterface:
    class: App\Repository\AccessTokenRepository
    decorates: 'League\Bundle\OAuth2ServerBundle\Repository\AccessTokenRepository'

  App\Service\CartAddService:
    arguments:
      $entityManager: '@doctrine.orm.entity_manager'
  App\EventListener\OrderConfirmedListener:
    arguments:
      $fromEmail: '%env(MAILER_FROM)%'
  App\EventListener\ProductDepletedListener:
    tags:
      - { name: 'kernel.event_listener', event: 'product.depleted', method: 'onProductDepleted' }
  App\Service\AuthGRPCService:
    arguments:
      $authServiceDsn: '%env(GRPC_AUTH_SERVICE_DSN)%'
      $userServiceDsn: '%env(GRPC_USER_SERVICE_DSN)%'
  App\Security\ProductVoter:
    tags: [ 'security.voter' ]
  App\Security\SubscriptionPlanVoter:
    tags: [ 'security.voter' ]
  App\Security\OrderStatusVoter:
    tags: [ 'security.voter' ]