parameters:
  .container.dumper.inline_factories: true
services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $fromEmail: '%env(MAILER_FROM)%'
      $authServiceDsn: '%env(GRPC_AUTH_SERVICE_DSN)%'
      $userServiceDsn: '%env(GRPC_USER_SERVICE_DSN)%'
      $cartItemMaxCapacity: '%env(CART_ITEM_MAX_CAPACITY)%'
      $privateJWTKey: '%env(JWT_ACCESS_TOKEN_PRIVATE_KEY)%'
  Redis:
    class: Redis
    calls:
      - connect:
          - '%env(REDIS_HOST)%'
          - '%env(int:REDIS_PORT)%'
      - auth:
          - '%env(REDIS_PASSWORD)%'
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
      - '../src/Tests/'

  Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler:
    arguments:
      - '@Redis'

  app.twig_extension:
    class: Twig\DeferredExtension\DeferredExtension
    public: false
    tags:
      - { name: twig.extension }

  League\OAuth2\Server\Repositories\AccessTokenRepositoryInterface:
    class: App\Repository\AccessTokenRepository
    decorates: 'League\Bundle\OAuth2ServerBundle\Repository\AccessTokenRepository'

  App\Security\Contracts\UserRegistrarInterface: '@App\Security\Registration\AuthApiUserRegistrar'
  App\Client\AuthClientInterface $authApiGRPCClient: '@App\Client\GRPC\AuthApiGRPCClient'
