<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth_service.proto

namespace App\grpc\GPBMetadata;

class AuthService
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \App\grpc\GPBMetadata\RpcSignin::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aba010a12617574685f736572766963652e70726f746f120a696e74727670726f746f325a0a0b4175746853657276696365124b0a0a5369676e496e55736572121b2e696e74727670726f746f2e5369676e496e55736572496e7075741a1e2e696e74727670726f746f2e5369676e496e55736572526573706f6e7365220042345a326769746875622e636f6d2f526166616c53616c77612f696e746572766965772d6170702d7372762f696e74727670726f746f620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

