<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc_signin.proto

namespace App\grpc\GPBMetadata;

class RpcSignin
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae6010a107270635f7369676e696e2e70726f746f120a696e74727670726f746f22350a0f5369676e496e55736572496e70757412100a08757365726e616d6518012001280912100a0870617373776f726418022001280922510a125369676e496e55736572526573706f6e7365120e0a0673746174757318012001280912140a0c6163636573735f746f6b656e18022001280912150a0d726566726573685f746f6b656e18032001280942345a326769746875622e636f6d2f526166616c53616c77612f696e746572766965772d6170702d7372762f696e74727670726f746f620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

