<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_service.proto

namespace App\grpc\GPBMetadata;

class UserService
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \App\grpc\GPBMetadata\User::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab4010a12757365725f736572766963652e70726f746f120a696e74727670726f746f32540a0b557365725365727669636512450a0b4765745573657242794964121a2e696e74727670726f746f2e47657455736572526571756573741a182e696e74727670726f746f2e55736572526573706f6e7365220042345a326769746875622e636f6d2f526166616c53616c77612f696e746572766965772d6170702d7372762f696e74727670726f746f620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

