deptrac:
  ignore_uncovered_internal_classes: false
  analyser:
    types:
      - class
      - class_superglobal
      - file
      - function
      - function_superglobal
      - function_call
  paths:
    - ../../src
  exclude_files:
    - '#.*test.*#'
  layers:
    - name: Controllers
      collectors:
        - type: classLike
          value: .*Controller.*
    - name: Commands
      collectors:
        - type: classLike
          value: .*Command.*
    - name: Repositories
      collectors:
        - type: classLike
          value: .*Repository.*
    - name: Services
      collectors:
        - type: classLike
          value: .*Service.*
    - name: Entities
      collectors:
        - type: attribute
          value: Doctrine\ORM\Mapping\Entity
    - name: Symfony
      collectors:
        - type: directory
          value: ../../vendor/symfony/.*
  ruleset:
    Controllers:
      - Services
      - Entities
      - Events
    Services:
      - Repositories
    Repositories:
      - Entities
    Entities:
      - Repositories
    Commands:
      - Services
      - Repositories
  formatters:
    graphviz:
      point_to_groups: true

