deptrac:
  ignore_uncovered_internal_classes: false
  analyser:
    types:
      - class
      - class_superglobal
      - file
      - function
      - function_superglobal
      - function_call
  paths:
    - ../../src
  exclude_files:
    - '#.*test.*#'
  layers:
    - name: Controllers
      collectors:
        - type: bool
          must:
            - type: classLike
              value: .*Controller.*
          must_not:
            - type: class
              value: .*AbstractShopController.*
    - name: Commands
      collectors:
        - type: classLike
          value: .*Command.*
    - name: Repositories
      collectors:
        - type: bool
          must:
            - type: classLike
              value: .*Repository.*
            - type: extends
              value: Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository
    - name: Services
      collectors:
        - type: classLike
          value: .*Service.*
    - name: Entities
      collectors:
        - type: attribute
          value: Doctrine\ORM\Mapping\Entity
    - name: SymfonySerializer
      collectors:
        - type: classLike
          value: .*Symfony\Component\Serializer.*

  ruleset:
    Controllers:
      - Services
      - Entities
      - Events
    Services:
      - Repositories
      - Entities
    Repositories:
      - Services
      - Entities
    Entities:
      - Repositories
      - SymfonySerializer
    Commands:
      - Services
      - Repositories
    Workflows:
      - Services
  formatters:
    graphviz:
      point_to_groups: true

