deptrac:
  ignore_uncovered_internal_classes: false
  analyser:
    types:
      - class
      - class_superglobal
      - file
      - function
      - function_superglobal
      - function_call
  paths:
    - ../../src
    - ../../vendor/symfony/framework-bundle/Controller
    - ../../vendor/symfony/serializer/
  exclude_files:
    - '#.*test.*#'
    - '#.(Symfony\\Component).#'
    - '#.*App\\Protobuf\\*.#'
  layers:
    - name: AbstractController
      collectors:
        - type: bool
          must:
          - type: class
            value: .*AbstractShopController.*
          - type: extends
            value: Symfony\Bundle\FrameworkBundle\Controller\AbstractController
    - name: Controllers
      collectors:
        - type: bool
          must:
            - type: classLike
              value: .*App\\Controller.*
          must_not:
            - type: class
              value: .*AbstractShopController.*
    - name: Commands
      collectors:
        - type: classLike
          value: .*App\\Command.*
    - name: Repositories
      collectors:
        - type: bool
          must:
            - type: classLike
              value: .*Repository.*
            - type: extends
              value: Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository
    - name: Services
      collectors:
        - type: classLike
          value: .*App\\Service.*
    - name: Workflows
      collectors:
        - type: classLike
          value: .*App\\Workflow.*
    - name: Entities
      collectors:
        - type: attribute
          value: Doctrine\ORM\Mapping\Entity
    - name: SymfonyController
      collectors:
        - type: classLike
          value: .*Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController.*

  ruleset:
    AbstractController:
      - SymfonyController
    Controllers:
      - AbstractController
      - SymfonyController
      - Services
      - Workflows
      - Entities
      - Events
    Services:
      - Repositories
      - Entities
    Repositories:
      - Services
      - Entities
    Entities:
      - Repositories
      - SymfonySerializer
    Commands:
      - Services
      - Repositories
    Workflows:
      - Services
    SymfonyController: ~
  formatters:
    graphviz:
      point_to_groups: true

