name: "Architecture & Dependencies"
on:
  pull_request:
  push:
    branches:
      - main
      - develop
jobs:
  deptrac:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04 ]
        php-version: [ 8.2, 8.3 ]

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, xml, ctype, iconv, grpc
          coverage: none
          tools: composer

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: composer-${{ runner.os }}-${{ matrix.php-version }}-${{ hashFiles('composer.*') }}
          restore-keys: |
            composer-${{ runner.os }}-${{ matrix.php-version }}-
            composer-${{ runner.os }}-
            composer-

      - name: "Install dependencies with composer"
        run: composer install

      - name: "Run deptrac"
        run: vendor/bin/deptrac --config-file=config/analysis/deptrac.yaml --formatter=github-actions
