name: "PHPCS-Fixer"
on:
  push:
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, iconv, grpc
          coverage: pcov
          tools: cs2pr, composer
      - uses: "ramsey/composer-install@v3"
        with:
          composer-options: "--no-interaction --no-progress --quiet --prefer-dist"
          custom-cache-key: composer-${{ runner.os }}-${{ matrix.php-version }}-${{ hashFiles('composer.lock') }}

      - name: "PHPCS Standards Scan"
        run: vendor/bin/php-cs-fixer --config=config/analysis/php-cs-fixer.php --format=checkstyle fix --dry-run | cs2pr
