name: PHPStan lvl 8
on:
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:
  php-stan:
    runs-on: ubuntu-latest
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, iconv, grpc
          coverage: pcov
          tools: cs2pr, composer

      - uses: "ramsey/composer-install@v3"
        with:
          composer-options: "--no-interaction --no-progress --quiet --prefer-dist"
          custom-cache-key: composer-${{ runner.os }}-${{ matrix.php-version }}-${{ hashFiles('composer.lock') }}

      - name: PHPStan Scan cs2pr
        id: phpstan_scan
        run: vendor/bin/phpstan --configuration=config/analysis/phpstan.neon --error-format=checkstyle | cs2pr
        continue-on-error: true

      - name: PHPStan Scan githubactions
        id: phpstan_scan
        run: vendor/bin/phpstan --configuration=config/analysis/phpstan.neon
        continue-on-error: true
