# github action that checks code with Rector
name: Rector

on:
  push:
  pull_request:
    branches:
      - main
      - develop

jobs:
  Rector:
    name: Setting up CI environment
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, iconv, grpc
          coverage: pcov
          tools: cs2pr, composer
      - uses: "ramsey/composer-install@v3"
        with:
          composer-options: "--no-interaction --no-progress --quiet --prefer-dist"
          custom-cache-key: composer-${{ runner.os }}-${{ matrix.php-version }}-${{ hashFiles('composer.lock') }}
      - name: Rector Dry Run
        run: php vendor/bin/rector process --dry-run --config=rector.php
