# github action that checks code with Rector
name: Rector

on:
  push:
  pull_request:
    branches:
      - main
      - develop

jobs:
  Rector:
    name: Setting up CI environment
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, iconv, grpc
          coverage: pcov
          tools: cs2pr, composer
      - uses: "ramsey/composer-install@v3"
        with:
          composer-options: "--no-interaction --no-progress --quiet --prefer-dist"
          custom-cache-key: composer-${{ runner.os }}-${{ matrix.php-version }}-${{ hashFiles('composer.lock') }}
      - name: Rector Dry Run
        run: vendor/bin/rector process --config=rector.php --ansi

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '[rector] Rector fixes'
          commit_author: 'GitHub Action <actions@github.com>'
          commit_user_email: 'action@github.com'

#      - name: Check for Rector modified files
#        id: rector-git-check
#        run: echo ::set-output name=modified::$(if git diff --exit-code --no-patch; then echo "false"; else echo "true"; fi)
#
#      - name: Git config
#        if: steps.rector-git-check.outputs.modified == 'true'
#        run: |
#          git config --global user.name 'rector-bot'
#          git config --global user.email 'rector-bot@salwa.com.pl'
#          echo ::set-env name=COMMIT_MESSAGE::$(git log -1 --pretty=format:"%s")
#
#      - name: Commit Rector changes
#        if: steps.rector-git-check.outputs.modified == 'true'
#        run: git commit -am "[rector] ${COMMIT_MESSAGE}"
#
#      - name: Push changes
#        if: steps.rector-git-check.outputs.modified == 'true'
#        run: git push
