# github action that checks code with Rector
name: Rector

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup:
    name: Setting up CI environment
    runs-on: ubuntu-latest
    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
    - uses: actions/checkout@v3
    - name: Install Dependencies
      uses: ramsey/composer-install@v2
        
  rector:
    name: Running dry-run of rector
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Rector Cache
      uses: actions/cache@v3
      with:
        path: /tmp/rector
        key: ${{ runner.os }}-rector-${{ github.run_id }}
        restore-keys: ${{ runner.os }}-rector-

    - run: mkdir -p /tmp/rector

    - name: Rector Dry Run
      run: php vendor/bin/rector process --dry-run --config=rector.php
